version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: local-runner.Dockerfile
    expose:
      - 3000
      - 443
    ports:
      - 3000:3000
      - 443:443
    restart: always
    depends_on:
      - database
    volumes:
      - type: bind
        source: ./
        target: /opt/app/
        read_only: false
      # excluded directories
      - /opt/app/node_modules
      - /opt/dist
      - /opt/app/logs
      - /opt/app/database

  database:
    build:
      context: .
      dockerfile: database/Dockerfile
    expose:
      - 5432
    ports:
      - 5555:5432
    volumes:
      - nestjs-seed-local-data:/var/lib/postgresql/data

volumes:
  nestjs-seed-local-data:
